import type { SurveyInput } from "./types";
import type {
  AreaId,
  ClassId,
  CommitStyle,
  DayId,
  FreqId,
  MakeupId,
  PackId,
  PriorityId,
  TimeBucket,
  TravelId,
  WindowId,
} from "./constants";

type Draft = {
  firstName: string;
  liveArea: AreaId;
  workArea?: AreaId | "";
  convenientAreas: AreaId[];
  travel?: TravelId;
  preferredDays: DayId[];
  preferredTimes: TimeBucket[];
  timeWindows: WindowId[];
  classTypes: ClassId[];
  frequency?: FreqId;
  statedPrice: number;
  commitPrice: number;
  packages: PackId[];
  commitmentStyle: CommitStyle;
  makeup: MakeupId;
  studioPriorities: PriorityId[];
  trueYogaStudent?: boolean;
};

function row(d: Draft): SurveyInput {
  return {
    firstName: d.firstName,
    liveArea: d.liveArea,
    workArea: d.workArea ?? "",
    convenientAreas: d.convenientAreas,
    travel: d.travel ?? "nearby",
    preferredDays: d.preferredDays,
    preferredTimes: d.preferredTimes,
    timeWindows: d.timeWindows,
    classTypes: d.classTypes,
    frequency: d.frequency ?? "weekly",
    statedPrice: d.statedPrice,
    commitPrice: d.commitPrice,
    packages: d.packages,
    commitmentStyle: d.commitmentStyle,
    makeup: d.makeup,
    studioPriorities: d.studioPriorities,
    trueYogaStudent: d.trueYogaStudent ?? true,
  };
}

export const SEED_STUDENTS: SurveyInput[] = [
  // East — morning cluster (Tampines / Bedok). Many like Nila but hate 8-week lock-in.
  row({
    firstName: "Mei",
    liveArea: "tampines",
    workArea: "tanjong_pagar",
    convenientAreas: ["tampines", "bedok"],
    preferredDays: ["fri", "sat"],
    preferredTimes: ["morning"],
    timeWindows: ["0900", "1000"],
    classTypes: ["hatha", "yin"],
    statedPrice: 22,
    commitPrice: 18,
    packages: ["4pack", "8pack"],
    commitmentStyle: "flexible",
    makeup: "essential",
    studioPriorities: ["location_home", "mrt", "price"],
  }),
  row({
    firstName: "Priya",
    liveArea: "tampines",
    workArea: "tampines",
    convenientAreas: ["tampines", "pasir_ris", "bedok"],
    travel: "same",
    preferredDays: ["fri", "sat", "sun"],
    preferredTimes: ["morning", "early"],
    timeWindows: ["0730", "0900", "1000"],
    classTypes: ["hatha", "vinyasa", "beginners"],
    statedPrice: 20,
    commitPrice: 18,
    packages: ["8pack", "4pack"],
    commitmentStyle: "fixed",
    makeup: "valued",
    studioPriorities: ["location_home", "small_group", "same_slot"],
  }),
  row({
    firstName: "Hui Min",
    liveArea: "bedok",
    workArea: "bugis",
    convenientAreas: ["bedok", "tampines", "marine_parade"],
    preferredDays: ["sat", "sun"],
    preferredTimes: ["morning"],
    timeWindows: ["0900", "1000", "1100"],
    classTypes: ["vinyasa", "hatha"],
    statedPrice: 25,
    commitPrice: 20,
    packages: ["4pack", "monthly"],
    commitmentStyle: "flexible",
    makeup: "essential",
    studioPriorities: ["mrt", "mats", "price"],
  }),
  row({
    firstName: "Sarah",
    liveArea: "simei",
    workArea: "tanjong_pagar",
    convenientAreas: ["tampines", "bedok", "simei"],
    preferredDays: ["fri", "sat"],
    preferredTimes: ["morning"],
    timeWindows: ["0900", "1000"],
    classTypes: ["hatha", "restorative", "yin"],
    statedPrice: 22,
    commitPrice: 20,
    packages: ["4pack"],
    commitmentStyle: "flexible",
    makeup: "essential",
    studioPriorities: ["location_home", "parking", "small_group"],
  }),
  row({
    firstName: "Farah",
    liveArea: "pasir_ris",
    convenientAreas: ["tampines", "pasir_ris"],
    travel: "nearby",
    preferredDays: ["sat", "sun"],
    preferredTimes: ["morning", "early"],
    timeWindows: ["0730", "0900", "1000"],
    classTypes: ["vinyasa", "hatha"],
    statedPrice: 20,
    commitPrice: 18,
    packages: ["4pack", "dropin"],
    commitmentStyle: "flexible",
    makeup: "valued",
    studioPriorities: ["mrt", "price", "mats"],
  }),
  row({
    firstName: "Rachel",
    liveArea: "tampines",
    workArea: "orchard",
    convenientAreas: ["tampines", "bedok"],
    preferredDays: ["fri"],
    preferredTimes: ["morning"],
    timeWindows: ["0900"],
    classTypes: ["hatha"],
    statedPrice: 18,
    commitPrice: 18,
    packages: ["8pack"],
    commitmentStyle: "fixed",
    makeup: "no",
    studioPriorities: ["same_slot", "location_home", "small_group"],
  }),
  row({
    firstName: "Wei Ling",
    liveArea: "bedok",
    convenientAreas: ["bedok", "marine_parade", "tampines"],
    preferredDays: ["sat", "sun", "fri"],
    preferredTimes: ["morning"],
    timeWindows: ["1000", "1100", "0900"],
    classTypes: ["vinyasa", "ashtanga"],
    frequency: "twice",
    statedPrice: 25,
    commitPrice: 22,
    packages: ["monthly", "8pack"],
    commitmentStyle: "monthly",
    makeup: "valued",
    studioPriorities: ["mrt", "size", "mats"],
  }),
  row({
    firstName: "Joanne",
    liveArea: "tampines",
    convenientAreas: ["tampines"],
    travel: "same",
    preferredDays: ["fri", "wed"],
    preferredTimes: ["morning", "evening"],
    timeWindows: ["0900", "1830"],
    classTypes: ["hatha", "beginners", "yin"],
    statedPrice: 20,
    commitPrice: 18,
    packages: ["4pack"],
    commitmentStyle: "flexible",
    makeup: "essential",
    studioPriorities: ["location_home", "price", "parking"],
  }),
  row({
    firstName: "Elaine",
    liveArea: "bedok",
    workArea: "tanjong_pagar",
    convenientAreas: ["bedok", "tampines", "tanjong_pagar"],
    travel: "island",
    preferredDays: ["sat", "tue"],
    preferredTimes: ["morning", "lunch"],
    timeWindows: ["1000", "1215"],
    classTypes: ["vinyasa", "hatha", "pranayama"],
    statedPrice: 25,
    commitPrice: 20,
    packages: ["4pack", "8pack"],
    commitmentStyle: "flexible",
    makeup: "valued",
    studioPriorities: ["mrt", "location_work", "mats"],
  }),
  row({
    firstName: "Cheryl",
    liveArea: "marine_parade",
    convenientAreas: ["bedok", "marine_parade", "bugis"],
    preferredDays: ["sat", "sun"],
    preferredTimes: ["morning"],
    timeWindows: ["0900", "1000"],
    classTypes: ["yin", "hatha", "restorative"],
    statedPrice: 22,
    commitPrice: 20,
    packages: ["4pack"],
    commitmentStyle: "flexible",
    makeup: "valued",
    studioPriorities: ["mrt", "small_group", "mats"],
  }),
  row({
    firstName: "Nicole",
    liveArea: "tampines",
    convenientAreas: ["tampines", "bedok", "simei"],
    preferredDays: ["fri", "sat", "sun"],
    preferredTimes: ["morning", "early"],
    timeWindows: ["0730", "0900", "1000"],
    classTypes: ["hatha", "vinyasa", "therapy"],
    frequency: "twice",
    statedPrice: 25,
    commitPrice: 22,
    packages: ["8pack", "monthly"],
    commitmentStyle: "fixed",
    makeup: "no",
    studioPriorities: ["same_slot", "small_group", "location_home"],
  }),
  row({
    firstName: "Amanda",
    liveArea: "pasir_ris",
    convenientAreas: ["tampines", "pasir_ris", "bedok"],
    preferredDays: ["sat"],
    preferredTimes: ["morning"],
    timeWindows: ["1000", "1100"],
    classTypes: ["vinyasa", "beginners"],
    frequency: "occasional",
    statedPrice: 18,
    commitPrice: 15,
    packages: ["dropin"],
    commitmentStyle: "flexible",
    makeup: "essential",
    studioPriorities: ["price", "parking", "mrt"],
    trueYogaStudent: false,
  }),
  row({
    firstName: "Grace",
    liveArea: "simei",
    convenientAreas: ["tampines", "bedok"],
    preferredDays: ["fri", "sat"],
    preferredTimes: ["morning"],
    timeWindows: ["0900", "1000"],
    classTypes: ["hatha", "yin"],
    statedPrice: 20,
    commitPrice: 18,
    packages: ["8pack", "4pack"],
    commitmentStyle: "fixed",
    makeup: "valued",
    studioPriorities: ["location_home", "same_slot", "price"],
  }),
  row({
    firstName: "Lynn",
    liveArea: "tampines",
    workArea: "bugis",
    convenientAreas: ["tampines", "bugis"],
    preferredDays: ["fri", "wed"],
    preferredTimes: ["morning", "lunch"],
    timeWindows: ["0900", "1215"],
    classTypes: ["hatha", "pranayama"],
    statedPrice: 22,
    commitPrice: 18,
    packages: ["4pack"],
    commitmentStyle: "flexible",
    makeup: "essential",
    studioPriorities: ["location_home", "location_work", "mrt"],
  }),
  row({
    firstName: "Stephanie",
    liveArea: "bedok",
    convenientAreas: ["bedok", "tampines"],
    preferredDays: ["sat", "sun", "fri"],
    preferredTimes: ["morning"],
    timeWindows: ["0900", "1000", "1100"],
    classTypes: ["vinyasa", "hatha", "yin"],
    statedPrice: 22,
    commitPrice: 20,
    packages: ["4pack", "8pack"],
    commitmentStyle: "flexible",
    makeup: "valued",
    studioPriorities: ["mrt", "small_group", "price"],
  }),
  row({
    firstName: "Adeline",
    liveArea: "tampines",
    convenientAreas: ["tampines", "bedok"],
    preferredDays: ["sat"],
    preferredTimes: ["morning", "early"],
    timeWindows: ["0730", "0900", "1000"],
    classTypes: ["vinyasa", "ashtanga", "hatha"],
    frequency: "weekly",
    statedPrice: 25,
    commitPrice: 22,
    packages: ["8pack"],
    commitmentStyle: "fixed",
    makeup: "no",
    studioPriorities: ["small_group", "mats", "mrt"],
  }),

  // North-East — weekday evening, therapy-friendly
  row({
    firstName: "Ananya",
    liveArea: "amk",
    workArea: "amk",
    convenientAreas: ["amk", "bishan", "serangoon"],
    preferredDays: ["tue", "thu"],
    preferredTimes: ["evening"],
    timeWindows: ["1830", "1930"],
    classTypes: ["therapy", "hatha", "yin"],
    frequency: "weekly",
    statedPrice: 28,
    commitPrice: 25,
    packages: ["8pack"],
    commitmentStyle: "fixed",
    makeup: "valued",
    studioPriorities: ["same_slot", "small_group", "location_home"],
  }),
  row({
    firstName: "Deepa",
    liveArea: "serangoon",
    convenientAreas: ["serangoon", "amk", "hougang"],
    preferredDays: ["tue", "thu", "sat"],
    preferredTimes: ["evening", "morning"],
    timeWindows: ["1930", "1830", "1000"],
    classTypes: ["therapy", "yin", "restorative"],
    statedPrice: 25,
    commitPrice: 22,
    packages: ["8pack", "4pack"],
    commitmentStyle: "fixed",
    makeup: "valued",
    studioPriorities: ["mrt", "small_group", "mats"],
  }),
  row({
    firstName: "Kavitha",
    liveArea: "hougang",
    convenientAreas: ["hougang", "serangoon", "amk"],
    preferredDays: ["mon", "wed", "thu"],
    preferredTimes: ["evening"],
    timeWindows: ["1930", "1830"],
    classTypes: ["therapy", "hatha"],
    statedPrice: 25,
    commitPrice: 22,
    packages: ["8pack"],
    commitmentStyle: "fixed",
    makeup: "no",
    studioPriorities: ["location_home", "same_slot", "parking"],
  }),
  row({
    firstName: "Lakshmi",
    liveArea: "bishan",
    workArea: "novena",
    convenientAreas: ["bishan", "amk", "novena", "serangoon"],
    preferredDays: ["tue", "thu"],
    preferredTimes: ["evening"],
    timeWindows: ["1830", "1930"],
    classTypes: ["therapy", "hatha", "pranayama"],
    statedPrice: 28,
    commitPrice: 25,
    packages: ["8pack", "monthly"],
    commitmentStyle: "fixed",
    makeup: "valued",
    studioPriorities: ["mrt", "small_group", "location_work"],
  }),
  row({
    firstName: "Siti",
    liveArea: "punggol",
    convenientAreas: ["punggol", "hougang", "serangoon"],
    preferredDays: ["wed", "thu", "sat"],
    preferredTimes: ["evening", "morning"],
    timeWindows: ["1930", "1000"],
    classTypes: ["hatha", "yin", "beginners"],
    statedPrice: 20,
    commitPrice: 18,
    packages: ["4pack"],
    commitmentStyle: "flexible",
    makeup: "essential",
    studioPriorities: ["mrt", "price", "location_home"],
  }),
  row({
    firstName: "Nadia",
    liveArea: "amk",
    convenientAreas: ["amk", "bishan"],
    travel: "same",
    preferredDays: ["tue", "thu", "sun"],
    preferredTimes: ["evening"],
    timeWindows: ["1830", "1930"],
    classTypes: ["therapy", "restorative", "yin"],
    statedPrice: 25,
    commitPrice: 22,
    packages: ["8pack", "4pack"],
    commitmentStyle: "fixed",
    makeup: "valued",
    studioPriorities: ["location_home", "same_slot", "mats"],
  }),
  row({
    firstName: "Hannah",
    liveArea: "serangoon",
    workArea: "bugis",
    convenientAreas: ["serangoon", "amk", "bugis"],
    preferredDays: ["tue", "wed"],
    preferredTimes: ["evening"],
    timeWindows: ["1930"],
    classTypes: ["therapy", "vinyasa"],
    statedPrice: 22,
    commitPrice: 20,
    packages: ["4pack", "8pack"],
    commitmentStyle: "flexible",
    makeup: "essential",
    studioPriorities: ["mrt", "price", "small_group"],
  }),
  row({
    firstName: "Jasmine",
    liveArea: "amk",
    convenientAreas: ["amk", "serangoon", "bishan"],
    preferredDays: ["mon", "tue", "thu"],
    preferredTimes: ["evening"],
    timeWindows: ["1830", "1930"],
    classTypes: ["hatha", "therapy", "beginners"],
    frequency: "twice",
    statedPrice: 22,
    commitPrice: 20,
    packages: ["monthly", "8pack"],
    commitmentStyle: "monthly",
    makeup: "valued",
    studioPriorities: ["location_home", "small_group", "mrt"],
  }),
  row({
    firstName: "Esther",
    liveArea: "bishan",
    convenientAreas: ["bishan", "amk", "novena"],
    preferredDays: ["tue", "thu"],
    preferredTimes: ["evening"],
    timeWindows: ["1930", "1830"],
    classTypes: ["therapy", "yin"],
    statedPrice: 25,
    commitPrice: 22,
    packages: ["8pack"],
    commitmentStyle: "fixed",
    makeup: "no",
    studioPriorities: ["same_slot", "parking", "small_group"],
  }),
  row({
    firstName: "Rina",
    liveArea: "hougang",
    convenientAreas: ["hougang", "serangoon", "amk"],
    preferredDays: ["thu", "sat"],
    preferredTimes: ["evening", "morning"],
    timeWindows: ["1930", "0900"],
    classTypes: ["hatha", "vinyasa", "therapy"],
    statedPrice: 20,
    commitPrice: 18,
    packages: ["4pack"],
    commitmentStyle: "flexible",
    makeup: "essential",
    studioPriorities: ["price", "mrt", "location_home"],
  }),
  row({
    firstName: "Priyanka",
    liveArea: "serangoon",
    convenientAreas: ["serangoon", "amk"],
    preferredDays: ["tue", "thu", "sun"],
    preferredTimes: ["evening"],
    timeWindows: ["1830", "1930"],
    classTypes: ["therapy", "hatha", "pranayama"],
    statedPrice: 28,
    commitPrice: 25,
    packages: ["8pack", "private"],
    commitmentStyle: "fixed",
    makeup: "valued",
    studioPriorities: ["small_group", "same_slot", "mats"],
  }),

  // Central — lunch + Saturday specialist
  row({
    firstName: "Daniel",
    liveArea: "tanjong_pagar",
    workArea: "tanjong_pagar",
    convenientAreas: ["tanjong_pagar", "chinatown", "bugis"],
    travel: "same",
    preferredDays: ["tue", "thu", "sat"],
    preferredTimes: ["lunch", "early"],
    timeWindows: ["1215", "0730"],
    classTypes: ["ashtanga", "vinyasa"],
    frequency: "twice",
    statedPrice: 30,
    commitPrice: 25,
    packages: ["monthly", "8pack"],
    commitmentStyle: "monthly",
    makeup: "valued",
    studioPriorities: ["location_work", "mrt", "size"],
  }),
  row({
    firstName: "Marcus",
    liveArea: "novena",
    workArea: "orchard",
    convenientAreas: ["novena", "orchard", "bugis"],
    preferredDays: ["mon", "wed", "sat"],
    preferredTimes: ["lunch", "early"],
    timeWindows: ["1215", "0630", "0730"],
    classTypes: ["ashtanga", "vinyasa", "pranayama"],
    frequency: "few",
    statedPrice: 30,
    commitPrice: 28,
    packages: ["monthly"],
    commitmentStyle: "monthly",
    makeup: "no",
    studioPriorities: ["location_work", "mrt", "mats"],
  }),
  row({
    firstName: "Ben",
    liveArea: "bugis",
    workArea: "bugis",
    convenientAreas: ["bugis", "chinatown", "tanjong_pagar"],
    preferredDays: ["wed", "fri", "sat"],
    preferredTimes: ["lunch", "morning"],
    timeWindows: ["1215", "0730"],
    classTypes: ["vinyasa", "ashtanga", "hatha"],
    statedPrice: 25,
    commitPrice: 22,
    packages: ["4pack", "8pack"],
    commitmentStyle: "flexible",
    makeup: "essential",
    studioPriorities: ["mrt", "location_work", "price"],
  }),
  row({
    firstName: "Arun",
    liveArea: "chinatown",
    workArea: "tanjong_pagar",
    convenientAreas: ["chinatown", "tanjong_pagar", "bugis"],
    preferredDays: ["tue", "thu", "sat"],
    preferredTimes: ["lunch", "early"],
    timeWindows: ["1215", "0630"],
    classTypes: ["ashtanga"],
    statedPrice: 28,
    commitPrice: 25,
    packages: ["8pack", "monthly"],
    commitmentStyle: "fixed",
    makeup: "no",
    studioPriorities: ["same_slot", "mrt", "small_group"],
  }),
  row({
    firstName: "Catherine",
    liveArea: "orchard",
    workArea: "orchard",
    convenientAreas: ["orchard", "novena", "bugis"],
    preferredDays: ["sat", "sun"],
    preferredTimes: ["morning", "early"],
    timeWindows: ["0730", "0900"],
    classTypes: ["vinyasa", "ashtanga", "yin"],
    statedPrice: 28,
    commitPrice: 22,
    packages: ["4pack"],
    commitmentStyle: "flexible",
    makeup: "valued",
    studioPriorities: ["mrt", "mats", "size"],
  }),
  row({
    firstName: "Ken",
    liveArea: "tanjong_pagar",
    workArea: "tanjong_pagar",
    convenientAreas: ["tanjong_pagar", "bugis"],
    preferredDays: ["mon", "wed", "fri"],
    preferredTimes: ["lunch"],
    timeWindows: ["1215"],
    classTypes: ["vinyasa", "hatha"],
    frequency: "weekly",
    statedPrice: 25,
    commitPrice: 22,
    packages: ["4pack", "dropin"],
    commitmentStyle: "flexible",
    makeup: "essential",
    studioPriorities: ["location_work", "mrt", "price"],
  }),
  row({
    firstName: "Michelle",
    liveArea: "novena",
    convenientAreas: ["novena", "bishan", "orchard"],
    preferredDays: ["sat", "sun"],
    preferredTimes: ["morning"],
    timeWindows: ["0900", "1000"],
    classTypes: ["yin", "restorative", "hatha"],
    statedPrice: 25,
    commitPrice: 20,
    packages: ["4pack"],
    commitmentStyle: "flexible",
    makeup: "valued",
    studioPriorities: ["mrt", "small_group", "mats"],
  }),
  row({
    firstName: "Vishal",
    liveArea: "bugis",
    workArea: "tanjong_pagar",
    convenientAreas: ["bugis", "tanjong_pagar", "chinatown"],
    preferredDays: ["sat"],
    preferredTimes: ["early", "morning"],
    timeWindows: ["0630", "0730", "0900"],
    classTypes: ["ashtanga", "vinyasa"],
    statedPrice: 30,
    commitPrice: 25,
    packages: ["8pack"],
    commitmentStyle: "fixed",
    makeup: "no",
    studioPriorities: ["same_slot", "mrt", "small_group"],
  }),
  row({
    firstName: "Tom",
    liveArea: "tanjong_pagar",
    workArea: "tanjong_pagar",
    convenientAreas: ["tanjong_pagar"],
    travel: "same",
    preferredDays: ["tue", "thu"],
    preferredTimes: ["lunch"],
    timeWindows: ["1215"],
    classTypes: ["vinyasa", "ashtanga"],
    frequency: "occasional",
    statedPrice: 22,
    commitPrice: 18,
    packages: ["dropin"],
    commitmentStyle: "flexible",
    makeup: "essential",
    studioPriorities: ["location_work", "price"],
    trueYogaStudent: false,
  }),

  // Bridges — will travel, keep Nila
  row({
    firstName: "Xin Yi",
    liveArea: "tampines",
    workArea: "novena",
    convenientAreas: ["tampines", "novena", "amk"],
    travel: "island",
    preferredDays: ["tue", "sat"],
    preferredTimes: ["evening", "morning"],
    timeWindows: ["1930", "1000"],
    classTypes: ["hatha", "therapy", "yin"],
    statedPrice: 25,
    commitPrice: 22,
    packages: ["8pack", "4pack"],
    commitmentStyle: "flexible",
    makeup: "valued",
    studioPriorities: ["small_group", "mrt", "same_slot"],
  }),
  row({
    firstName: "Yasmin",
    liveArea: "bedok",
    workArea: "orchard",
    convenientAreas: ["bedok", "bugis", "orchard"],
    travel: "island",
    preferredDays: ["sat", "wed"],
    preferredTimes: ["morning", "lunch"],
    timeWindows: ["1000", "1215"],
    classTypes: ["vinyasa", "pranayama"],
    statedPrice: 25,
    commitPrice: 20,
    packages: ["monthly", "4pack"],
    commitmentStyle: "monthly",
    makeup: "valued",
    studioPriorities: ["mrt", "mats", "location_work"],
  }),
  row({
    firstName: "Fiona",
    liveArea: "serangoon",
    convenientAreas: ["serangoon", "bugis", "amk"],
    travel: "island",
    preferredDays: ["sat", "sun"],
    preferredTimes: ["morning"],
    timeWindows: ["0900", "1000"],
    classTypes: ["hatha", "vinyasa", "beginners"],
    statedPrice: 20,
    commitPrice: 18,
    packages: ["4pack"],
    commitmentStyle: "flexible",
    makeup: "essential",
    studioPriorities: ["mrt", "price", "small_group"],
    trueYogaStudent: false,
  }),
  row({
    firstName: "Sharon",
    liveArea: "amk",
    convenientAreas: ["amk", "tampines"],
    travel: "island",
    preferredDays: ["fri", "sat"],
    preferredTimes: ["morning"],
    timeWindows: ["0900", "1000"],
    classTypes: ["hatha", "yin"],
    statedPrice: 22,
    commitPrice: 18,
    packages: ["4pack", "8pack"],
    commitmentStyle: "flexible",
    makeup: "valued",
    studioPriorities: ["small_group", "price", "mrt"],
  }),
  row({
    firstName: "Li Wei",
    liveArea: "bishan",
    workArea: "tanjong_pagar",
    convenientAreas: ["bishan", "tanjong_pagar", "novena"],
    travel: "nearby",
    preferredDays: ["wed", "sat"],
    preferredTimes: ["lunch", "morning"],
    timeWindows: ["1215", "0900"],
    classTypes: ["vinyasa", "hatha"],
    statedPrice: 22,
    commitPrice: 20,
    packages: ["4pack"],
    commitmentStyle: "flexible",
    makeup: "essential",
    studioPriorities: ["location_work", "mrt", "price"],
  }),
  row({
    firstName: "Raj",
    liveArea: "hougang",
    convenientAreas: ["hougang", "serangoon", "amk"],
    preferredDays: ["sat", "sun"],
    preferredTimes: ["early", "morning"],
    timeWindows: ["0730", "0900"],
    classTypes: ["ashtanga", "vinyasa"],
    statedPrice: 22,
    commitPrice: 20,
    packages: ["8pack"],
    commitmentStyle: "fixed",
    makeup: "no",
    studioPriorities: ["same_slot", "parking", "small_group"],
  }),
];
